/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dsi.intranet.eprocurement.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.dsi.intranet.eprocurement.model.EprocurementLocation;
import com.dsi.intranet.eprocurement.service.EprocurementLocationLocalServiceUtil;

/**
 * The extended model base implementation for the EprocurementLocation service. Represents a row in the &quot;eproc_location&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EprocurementLocationImpl}.
 * </p>
 *
 * @author CIGNEX Technologies
 * @see EprocurementLocationImpl
 * @see EprocurementLocation
 * @generated
 */
@ProviderType
public abstract class EprocurementLocationBaseImpl
	extends EprocurementLocationModelImpl implements EprocurementLocation {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a eprocurement location model instance should use the {@link EprocurementLocation} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EprocurementLocationLocalServiceUtil.addEprocurementLocation(this);
		}
		else {
			EprocurementLocationLocalServiceUtil.updateEprocurementLocation(this);
		}
	}
}