/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dsi.intranet.eprocurement.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.dsi.intranet.eprocurement.model.WorkflowDefinition;
import com.dsi.intranet.eprocurement.service.WorkflowDefinitionLocalServiceUtil;

/**
 * The extended model base implementation for the WorkflowDefinition service. Represents a row in the &quot;eproc_workflow_definition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WorkflowDefinitionImpl}.
 * </p>
 *
 * @author CIGNEX Technologies
 * @see WorkflowDefinitionImpl
 * @see WorkflowDefinition
 * @generated
 */
@ProviderType
public abstract class WorkflowDefinitionBaseImpl
	extends WorkflowDefinitionModelImpl implements WorkflowDefinition {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a workflow definition model instance should use the {@link WorkflowDefinition} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			WorkflowDefinitionLocalServiceUtil.addWorkflowDefinition(this);
		}
		else {
			WorkflowDefinitionLocalServiceUtil.updateWorkflowDefinition(this);
		}
	}
}