/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dsi.intranet.eprocurement.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the EprocurementLocation service. Represents a row in the &quot;eproc_location&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dsi.intranet.eprocurement.model.impl.EprocurementLocationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dsi.intranet.eprocurement.model.impl.EprocurementLocationImpl}.
 * </p>
 *
 * @author CIGNEX Technologies
 * @see EprocurementLocation
 * @see com.dsi.intranet.eprocurement.model.impl.EprocurementLocationImpl
 * @see com.dsi.intranet.eprocurement.model.impl.EprocurementLocationModelImpl
 * @generated
 */
@ProviderType
public interface EprocurementLocationModel extends BaseModel<EprocurementLocation>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a eprocurement location model instance should use the {@link EprocurementLocation} interface instead.
	 */

	/**
	 * Returns the primary key of this eprocurement location.
	 *
	 * @return the primary key of this eprocurement location
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this eprocurement location.
	 *
	 * @param primaryKey the primary key of this eprocurement location
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the location ID of this eprocurement location.
	 *
	 * @return the location ID of this eprocurement location
	 */
	@AutoEscape
	public String getLocationId();

	/**
	 * Sets the location ID of this eprocurement location.
	 *
	 * @param locationId the location ID of this eprocurement location
	 */
	public void setLocationId(String locationId);

	/**
	 * Returns the company ID of this eprocurement location.
	 *
	 * @return the company ID of this eprocurement location
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this eprocurement location.
	 *
	 * @param companyId the company ID of this eprocurement location
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the location of this eprocurement location.
	 *
	 * @return the location of this eprocurement location
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this eprocurement location.
	 *
	 * @param location the location of this eprocurement location
	 */
	public void setLocation(String location);

	/**
	 * Returns the flow type of this eprocurement location.
	 *
	 * @return the flow type of this eprocurement location
	 */
	@AutoEscape
	public String getFlowType();

	/**
	 * Sets the flow type of this eprocurement location.
	 *
	 * @param flowType the flow type of this eprocurement location
	 */
	public void setFlowType(String flowType);

	/**
	 * Returns the location type of this eprocurement location.
	 *
	 * @return the location type of this eprocurement location
	 */
	@AutoEscape
	public String getLocationType();

	/**
	 * Sets the location type of this eprocurement location.
	 *
	 * @param locationType the location type of this eprocurement location
	 */
	public void setLocationType(String locationType);

	/**
	 * Returns the address of this eprocurement location.
	 *
	 * @return the address of this eprocurement location
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this eprocurement location.
	 *
	 * @param address the address of this eprocurement location
	 */
	public void setAddress(String address);

	/**
	 * Returns the personnel area of this eprocurement location.
	 *
	 * @return the personnel area of this eprocurement location
	 */
	@AutoEscape
	public String getPersonnelArea();

	/**
	 * Sets the personnel area of this eprocurement location.
	 *
	 * @param personnelArea the personnel area of this eprocurement location
	 */
	public void setPersonnelArea(String personnelArea);

	/**
	 * Returns the personnel sub area of this eprocurement location.
	 *
	 * @return the personnel sub area of this eprocurement location
	 */
	@AutoEscape
	public String getPersonnelSubArea();

	/**
	 * Sets the personnel sub area of this eprocurement location.
	 *
	 * @param personnelSubArea the personnel sub area of this eprocurement location
	 */
	public void setPersonnelSubArea(String personnelSubArea);

	/**
	 * Returns the building number of this eprocurement location.
	 *
	 * @return the building number of this eprocurement location
	 */
	@AutoEscape
	public String getBuildingNumber();

	/**
	 * Sets the building number of this eprocurement location.
	 *
	 * @param buildingNumber the building number of this eprocurement location
	 */
	public void setBuildingNumber(String buildingNumber);

	/**
	 * Returns the app name of this eprocurement location.
	 *
	 * @return the app name of this eprocurement location
	 */
	@AutoEscape
	public String getAppName();

	/**
	 * Sets the app name of this eprocurement location.
	 *
	 * @param appName the app name of this eprocurement location
	 */
	public void setAppName(String appName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EprocurementLocation eprocurementLocation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EprocurementLocation> toCacheModel();

	@Override
	public EprocurementLocation toEscapedModel();

	@Override
	public EprocurementLocation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}