/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dsi.intranet.eprocurement.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Item service. Represents a row in the &quot;eproc_item&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dsi.intranet.eprocurement.model.impl.ItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dsi.intranet.eprocurement.model.impl.ItemImpl}.
 * </p>
 *
 * @author CIGNEX Technologies
 * @see Item
 * @see com.dsi.intranet.eprocurement.model.impl.ItemImpl
 * @see com.dsi.intranet.eprocurement.model.impl.ItemModelImpl
 * @generated
 */
@ProviderType
public interface ItemModel extends BaseModel<Item>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item model instance should use the {@link Item} interface instead.
	 */

	/**
	 * Returns the primary key of this item.
	 *
	 * @return the primary key of this item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item.
	 *
	 * @param primaryKey the primary key of this item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item ID of this item.
	 *
	 * @return the item ID of this item
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this item.
	 *
	 * @param itemId the item ID of this item
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the item name of this item.
	 *
	 * @return the item name of this item
	 */
	@AutoEscape
	public String getItemName();

	/**
	 * Sets the item name of this item.
	 *
	 * @param itemName the item name of this item
	 */
	public void setItemName(String itemName);

	/**
	 * Returns the item description of this item.
	 *
	 * @return the item description of this item
	 */
	@AutoEscape
	public String getItemDescription();

	/**
	 * Sets the item description of this item.
	 *
	 * @param itemDescription the item description of this item
	 */
	public void setItemDescription(String itemDescription);

	/**
	 * Returns the quantity of this item.
	 *
	 * @return the quantity of this item
	 */
	public long getQuantity();

	/**
	 * Sets the quantity of this item.
	 *
	 * @param quantity the quantity of this item
	 */
	public void setQuantity(long quantity);

	/**
	 * Returns the cost of this item.
	 *
	 * @return the cost of this item
	 */
	public double getCost();

	/**
	 * Sets the cost of this item.
	 *
	 * @param cost the cost of this item
	 */
	public void setCost(double cost);

	/**
	 * Returns the original cost of this item.
	 *
	 * @return the original cost of this item
	 */
	public double getOriginalCost();

	/**
	 * Sets the original cost of this item.
	 *
	 * @param originalCost the original cost of this item
	 */
	public void setOriginalCost(double originalCost);

	/**
	 * Returns the wbselement of this item.
	 *
	 * @return the wbselement of this item
	 */
	@AutoEscape
	public String getWbselement();

	/**
	 * Sets the wbselement of this item.
	 *
	 * @param wbselement the wbselement of this item
	 */
	public void setWbselement(String wbselement);

	/**
	 * Returns the gl acc no of this item.
	 *
	 * @return the gl acc no of this item
	 */
	@AutoEscape
	public String getGlAccNo();

	/**
	 * Sets the gl acc no of this item.
	 *
	 * @param glAccNo the gl acc no of this item
	 */
	public void setGlAccNo(String glAccNo);

	/**
	 * Returns the cost center of this item.
	 *
	 * @return the cost center of this item
	 */
	@AutoEscape
	public String getCostCenter();

	/**
	 * Sets the cost center of this item.
	 *
	 * @param costCenter the cost center of this item
	 */
	public void setCostCenter(String costCenter);

	/**
	 * Returns the request ID of this item.
	 *
	 * @return the request ID of this item
	 */
	public long getRequestId();

	/**
	 * Sets the request ID of this item.
	 *
	 * @param requestId the request ID of this item
	 */
	public void setRequestId(long requestId);

	/**
	 * Returns the item in stock of this item.
	 *
	 * @return the item in stock of this item
	 */
	public boolean getItemInStock();

	/**
	 * Returns <code>true</code> if this item is item in stock.
	 *
	 * @return <code>true</code> if this item is item in stock; <code>false</code> otherwise
	 */
	public boolean isItemInStock();

	/**
	 * Sets whether this item is item in stock.
	 *
	 * @param itemInStock the item in stock of this item
	 */
	public void setItemInStock(boolean itemInStock);

	/**
	 * Returns the vendor code of this item.
	 *
	 * @return the vendor code of this item
	 */
	@AutoEscape
	public String getVendorCode();

	/**
	 * Sets the vendor code of this item.
	 *
	 * @param vendorCode the vendor code of this item
	 */
	public void setVendorCode(String vendorCode);

	/**
	 * Returns the purchase order of this item.
	 *
	 * @return the purchase order of this item
	 */
	@AutoEscape
	public String getPurchaseOrder();

	/**
	 * Sets the purchase order of this item.
	 *
	 * @param purchaseOrder the purchase order of this item
	 */
	public void setPurchaseOrder(String purchaseOrder);

	/**
	 * Returns the recieved date of this item.
	 *
	 * @return the recieved date of this item
	 */
	public Date getRecievedDate();

	/**
	 * Sets the recieved date of this item.
	 *
	 * @param recievedDate the recieved date of this item
	 */
	public void setRecievedDate(Date recievedDate);

	/**
	 * Returns the returned date of this item.
	 *
	 * @return the returned date of this item
	 */
	public Date getReturnedDate();

	/**
	 * Sets the returned date of this item.
	 *
	 * @param returnedDate the returned date of this item
	 */
	public void setReturnedDate(Date returnedDate);

	/**
	 * Returns the asset info of this item.
	 *
	 * @return the asset info of this item
	 */
	@AutoEscape
	public String getAssetInfo();

	/**
	 * Sets the asset info of this item.
	 *
	 * @param assetInfo the asset info of this item
	 */
	public void setAssetInfo(String assetInfo);

	/**
	 * Returns the returned assets of this item.
	 *
	 * @return the returned assets of this item
	 */
	@AutoEscape
	public String getReturnedAssets();

	/**
	 * Sets the returned assets of this item.
	 *
	 * @param returnedAssets the returned assets of this item
	 */
	public void setReturnedAssets(String returnedAssets);

	/**
	 * Returns the created by of this item.
	 *
	 * @return the created by of this item
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this item.
	 *
	 * @param createdBy the created by of this item
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the created date of this item.
	 *
	 * @return the created date of this item
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this item.
	 *
	 * @param createdDate the created date of this item
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified by of this item.
	 *
	 * @return the modified by of this item
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this item.
	 *
	 * @param modifiedBy the modified by of this item
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the modified date of this item.
	 *
	 * @return the modified date of this item
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this item.
	 *
	 * @param modifiedDate the modified date of this item
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the company ID of this item.
	 *
	 * @return the company ID of this item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this item.
	 *
	 * @param companyId the company ID of this item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this item.
	 *
	 * @return the group ID of this item
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this item.
	 *
	 * @param groupId the group ID of this item
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Item item);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Item> toCacheModel();

	@Override
	public Item toEscapedModel();

	@Override
	public Item toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}