/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dsi.intranet.eprocurement.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RequestAttachment service. Represents a row in the &quot;eproc_request_attachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dsi.intranet.eprocurement.model.impl.RequestAttachmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dsi.intranet.eprocurement.model.impl.RequestAttachmentImpl}.
 * </p>
 *
 * @author CIGNEX Technologies
 * @see RequestAttachment
 * @see com.dsi.intranet.eprocurement.model.impl.RequestAttachmentImpl
 * @see com.dsi.intranet.eprocurement.model.impl.RequestAttachmentModelImpl
 * @generated
 */
@ProviderType
public interface RequestAttachmentModel extends BaseModel<RequestAttachment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a request attachment model instance should use the {@link RequestAttachment} interface instead.
	 */

	/**
	 * Returns the primary key of this request attachment.
	 *
	 * @return the primary key of this request attachment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this request attachment.
	 *
	 * @param primaryKey the primary key of this request attachment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the request attachment ID of this request attachment.
	 *
	 * @return the request attachment ID of this request attachment
	 */
	public long getRequestAttachmentId();

	/**
	 * Sets the request attachment ID of this request attachment.
	 *
	 * @param requestAttachmentId the request attachment ID of this request attachment
	 */
	public void setRequestAttachmentId(long requestAttachmentId);

	/**
	 * Returns the request ID of this request attachment.
	 *
	 * @return the request ID of this request attachment
	 */
	public long getRequestId();

	/**
	 * Sets the request ID of this request attachment.
	 *
	 * @param requestId the request ID of this request attachment
	 */
	public void setRequestId(long requestId);

	/**
	 * Returns the file entry ID of this request attachment.
	 *
	 * @return the file entry ID of this request attachment
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this request attachment.
	 *
	 * @param fileEntryId the file entry ID of this request attachment
	 */
	public void setFileEntryId(long fileEntryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RequestAttachment requestAttachment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RequestAttachment> toCacheModel();

	@Override
	public RequestAttachment toEscapedModel();

	@Override
	public RequestAttachment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}