/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dsi.intranet.eprocurement.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkflowReview service. Represents a row in the &quot;eproc_workflow_review&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dsi.intranet.eprocurement.model.impl.WorkflowReviewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dsi.intranet.eprocurement.model.impl.WorkflowReviewImpl}.
 * </p>
 *
 * @author CIGNEX Technologies
 * @see WorkflowReview
 * @see com.dsi.intranet.eprocurement.model.impl.WorkflowReviewImpl
 * @see com.dsi.intranet.eprocurement.model.impl.WorkflowReviewModelImpl
 * @generated
 */
@ProviderType
public interface WorkflowReviewModel extends AttachedModel,
	BaseModel<WorkflowReview>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a workflow review model instance should use the {@link WorkflowReview} interface instead.
	 */

	/**
	 * Returns the primary key of this workflow review.
	 *
	 * @return the primary key of this workflow review
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this workflow review.
	 *
	 * @param primaryKey the primary key of this workflow review
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the workflow review ID of this workflow review.
	 *
	 * @return the workflow review ID of this workflow review
	 */
	public long getWorkflowReviewId();

	/**
	 * Sets the workflow review ID of this workflow review.
	 *
	 * @param workflowReviewId the workflow review ID of this workflow review
	 */
	public void setWorkflowReviewId(long workflowReviewId);

	/**
	 * Returns the workflow request ID of this workflow review.
	 *
	 * @return the workflow request ID of this workflow review
	 */
	public long getWorkflowRequestId();

	/**
	 * Sets the workflow request ID of this workflow review.
	 *
	 * @param workflowRequestId the workflow request ID of this workflow review
	 */
	public void setWorkflowRequestId(long workflowRequestId);

	/**
	 * Returns the fully qualified class name of this workflow review.
	 *
	 * @return the fully qualified class name of this workflow review
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this workflow review.
	 *
	 * @return the class name ID of this workflow review
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this workflow review.
	 *
	 * @param classNameId the class name ID of this workflow review
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this workflow review.
	 *
	 * @return the class pk of this workflow review
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this workflow review.
	 *
	 * @param classPK the class pk of this workflow review
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the updated by of this workflow review.
	 *
	 * @return the updated by of this workflow review
	 */
	public long getUpdatedBy();

	/**
	 * Sets the updated by of this workflow review.
	 *
	 * @param updatedBy the updated by of this workflow review
	 */
	public void setUpdatedBy(long updatedBy);

	/**
	 * Returns the updated to status of this workflow review.
	 *
	 * @return the updated to status of this workflow review
	 */
	@AutoEscape
	public String getUpdatedToStatus();

	/**
	 * Sets the updated to status of this workflow review.
	 *
	 * @param updatedToStatus the updated to status of this workflow review
	 */
	public void setUpdatedToStatus(String updatedToStatus);

	/**
	 * Returns the next stage of this workflow review.
	 *
	 * @return the next stage of this workflow review
	 */
	@AutoEscape
	public String getNextStage();

	/**
	 * Sets the next stage of this workflow review.
	 *
	 * @param nextStage the next stage of this workflow review
	 */
	public void setNextStage(String nextStage);

	/**
	 * Returns the is approver role of this workflow review.
	 *
	 * @return the is approver role of this workflow review
	 */
	@AutoEscape
	public String getIsApproverRole();

	/**
	 * Sets the is approver role of this workflow review.
	 *
	 * @param isApproverRole the is approver role of this workflow review
	 */
	public void setIsApproverRole(String isApproverRole);

	/**
	 * Returns the updated date of this workflow review.
	 *
	 * @return the updated date of this workflow review
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this workflow review.
	 *
	 * @param updatedDate the updated date of this workflow review
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the approver comments of this workflow review.
	 *
	 * @return the approver comments of this workflow review
	 */
	@AutoEscape
	public String getApproverComments();

	/**
	 * Sets the approver comments of this workflow review.
	 *
	 * @param approverComments the approver comments of this workflow review
	 */
	public void setApproverComments(String approverComments);

	/**
	 * Returns the email comments of this workflow review.
	 *
	 * @return the email comments of this workflow review
	 */
	@AutoEscape
	public String getEmailComments();

	/**
	 * Sets the email comments of this workflow review.
	 *
	 * @param emailComments the email comments of this workflow review
	 */
	public void setEmailComments(String emailComments);

	/**
	 * Returns the company ID of this workflow review.
	 *
	 * @return the company ID of this workflow review
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this workflow review.
	 *
	 * @param companyId the company ID of this workflow review
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this workflow review.
	 *
	 * @return the group ID of this workflow review
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this workflow review.
	 *
	 * @param groupId the group ID of this workflow review
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WorkflowReview workflowReview);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WorkflowReview> toCacheModel();

	@Override
	public WorkflowReview toEscapedModel();

	@Override
	public WorkflowReview toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}